### PR TITLE
#64854 Add preserveduplicates option to ResourceList

### PR DESCRIPTION
**Pull request by TheConstructor**
I propose this to solve https://bz.apache.org/bugzilla/show_bug.cgi?id=64854

### CODE REVIEW

**Comment by TheConstructor** [comment]
I just send the e-mail with the ICLA. Feel free to improve my code.

**Comment by bodewig** [comment]
You removed the `volatile` attribute `cached´ from `ResourceList`. Th way code is structured now there is a race-condition where one thread my be using a cache that hasn't been initialized completely. I'm afraid you need to bring back `cached` redundant as it may seem.

Apart from that I've only got a few nits:

* I'm not sure about the name `WriteableResourceCollection` - `AppendableResourceCollection` maybe?
* please add since markers with 1.10.10 to new classes/methods and to the manual
* more importantly, add yourself to CONTRIBUTORS (plain text) and contributors.xml. The files are supposed to be ordered lexicographically by first name.

Many thanks.

**Comment by TheConstructor** [comment]
I checked that `cachedResources` is only ever accessed through `cache()`, which is `synchronized`. Is this really a problem? Would declaring `cachedResources` `volatile` and/or assigning the field just after populating the cache help in your opinion?

To your nits:
- I am happy to change the name
- I wasn't quite sure which version could be next, so I thought it would be good to have something in place, where I can pick up work. -> will insert the version
- Ok

**Comment by bodewig** [comment]
I completely overlooked `cache` was synchronized. Since all read an write operations on `cachedResources` are synchronized, I don't think a problem exists there. Sorry.

**Comment by TheConstructor** [comment]
@bodewig Thank you again for looking into this and my other PR!

**Pull request merged**
