### PR TITLE
Add HTML validation check

### PR DESCRIPTION
**Pull request by twogee**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/98/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/99/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/100/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/104/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/106/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/101/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/107/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/111/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/105/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/116/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/110/

**Comment by janmaterne** [comment]
Summerize the changes:

- Add new tool "Nu HTML Validator" for checking manual and site
  check.xml: new target 'vnu'
- add attribute: <html>  -->  <html lang="en">
- remove <meta http-equiv="Content-Language" content="en-us">
- manual/tutorial-tasks-filesets-properties.html
  added >>scope="col"<< to table-header
- src/main/org/apache/tools/ant/property/package.html
  -- added html/head/title
  -- fixed typo s/ant/Ant/
- src/main/org/apache/tools/ant/taskdefs/optional/sos/package.html
  -- added title
  -- added DOCTYPE-html
- src/main/org/apache/tools/ant/types/resolver/package.html
  dito

**Comment by janmaterne** [comment]
I like the idea of checking the html files.
But why are these changes required? Only because a tool sais that is not enough for me. Do you have pointers to some specs?

**Comment by twogee** [comment]
The goal is to follow HTML 5 spec (except for index.html where we still have frames).
What is missing is doctype and lang attribute instead of meta tags.
scope attribute on th is an accessibility requirement (there was a Bugzilla for that).

**Comment by twogee** [comment]
Recommendations re [doctype](https://www.w3.org/QA/Tips/Doctype), [language declaration](https://www.w3.org/International/questions/qa-html-language-declarations), [scope attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#The_scope_attribute), also [WAI table tutorial](https://www.w3.org/WAI/tutorials/tables/)

**Comment by janmaterne** [comment]
Thanks for the links, sounds reasonable.
Two things I found:
1. maybe you should add a short paragraph in the &lt;description> section like for the other tools
2. why you named the target "vnu"? Something like "html-check" sounds more descriptive. Compare to "dependency-check" instead of "owasp"

**Comment by janmaterne** [comment]
Just summarize/quote the link contents:
- **doctype**: that declaration was used in HTML5 to distinguish between a standards-compliant parsing mode and a so-called quirks parsing mode.
- **&lt;meta http-equiv="Content-Language">**: Due to long-standing confusions and inconsistent implementations of this element, the HTML5 specification made this non-conforming in HTML, so you should no longer use it.
- **&lt;th scope="row|col">**: tell screenreaders exactly what cells the header is a header for

**Comment by janmaterne** [comment]
Tool "Copyright (c) 2013-2018 Mozilla Foundation" (https://github.com/validator/validator/blob/master/src/nu/validator/client/SimpleCommandLineValidator.java), so license seems to be ok.

Runs fine. Errors are printed to the console.

It seems that the tool does not support writing a report to file.
Could you try to create a report file with Ant (&lt;redirector>)? So this target would behave like the other report-targets.

**Comment by janmaterne** [comment]
This PR can't be responsible for the failing tests as the sources or test files are not touched.

Failing tests are:
    src.tests.antunit.types.resources.test_xml.testhttpurl2
    src.tests.antunit.taskdefs.get-test_xml.testTemporaryRedirect
    src.tests.antunit.taskdefs.get-test_xml.testNestedResources
    src.tests.antunit.taskdefs.get-test_xml.testInfiniteRedirect
    src.tests.antunit.taskdefs.gunzip-test_xml.testWithNonFileResourceToDir
    src.tests.antunit.taskdefs.gunzip-test_xml.testWithNonFileResourceToFile

**Comment by twogee** [comment]
Thanks for reviewing and excellent summaries.

These tests have failed multiple times previously; it looks like redirection tests cannot connect to external servers any longer. It is confusing, however, that they apparently pass in nightlies... 

Regarding redirection: java task has output/error (and outputproperty/errorproperty) attributes. Surely these would be sufficient for logging?

**Comment by janmaterne** [comment]
out|err-props could also work. Catch into prop, write prop to file and print. Give it a try.

**Comment by janmaterne** [comment]
Added the redirection to file and did a few renamings. Merged into master.

**Pull request merged**
