### PR TITLE
Use equals method of a string literal to prevent NPE and isEmpty() me…

### PR DESCRIPTION
**Pull request by reudismam**
…thod instead of comparing a String object with an empty string.

This change has already been done for some locations in the commit:
https://github.com/apache/ant/commit/b7d1e9bde44cb8e5233d6e70bb96e14cbb2f3e2d

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jaikiran** [comment]
this is ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/36/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/30/

**Comment by bodewig** [comment]
many thanks!

**Pull request closed without merging**
