### PR TITLE
Use the isEmpty method instead of comparing the value of size() to 0.

### PR DESCRIPTION
**Pull request by reudismam**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jaikiran** [comment]
this is ok to test

**Comment by jaikiran** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/36/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/42/

**Comment by jaikiran** [comment]
Thank for you the PR. This is now merged

**Pull request closed without merging**
