### PR TITLE
Added JDK 9 module system support to the Java Task

### PR DESCRIPTION
**Pull request by tzezula**
Added main module, modulepath and moduleupgradepath into Java task.

### CODE REVIEW

**Comment by bodewig** [comment]
Thanks a lot Tomas, I've merged your patch.

It would be good if you could also provide a patch the java task page inside of Ant's manual.

**Comment by tzezula** [comment]
Thanks Stefan, I will do a patch of Ant's java task manual.

**Comment by bodewig** [comment]
Great.

Our [CI builds](https://builds.apache.org/job/Ant-Build-Matrix/) on Windows are failing because the test `testModuleAndClassnameCommandLine` expects the module to be `TestModule/org.apache.Test` while in fact it is `TestModule\org.apache.Test`. Before I start fixing the code, am I correct in assuming the separator between module and classname always is a forward slash? I'm having a hard time finding any documentation.

**Comment by tzezula** [comment]
Sorry for that. I will get some Windows box for testing.
Yes, it's '/'.
The  -m option support either  <modulename>  or <modulename>/<mainclass>.

**Comment by bodewig** [comment]
don't worry and thanks for your support

**Comment by tzezula** [comment]
Hi Stefan
Here is a patch for the Java task page inside of Ant's manual. I've also updated the since tags to 1.9.7:
https://github.com/tzezula/ant/commit/aef407be4d33de09861a1f9677b2f15ea5ea8fdf

I've added a modulepathref attribute to the Java task to be symmetric with classpath:
https://github.com/tzezula/ant/commit/1e501f27ecc8f292ff028191e886a36d4b571d79

**Comment by bodewig** [comment]
I had a few merge conflicts as I already added the since tags, but I think I've got them resolved.

Many thanks.

**Comment by tzezula** [comment]
Thanks a lot Stefan!

**Pull request closed without merging**
