### PR TITLE
Make Changes to Support FTPS AntTaskDef that extends FTP but uses FTP…

### PR DESCRIPTION
**Pull request by sonyDeswal**
Make Changes to Support FTPS AntTaskDef that extends FTP but uses FTPSClient. Currently Ant Taskdef is not supporting FTPS.

### CODE REVIEW

**Comment by bodewig** [comment]
To me it looks as if this could become a new "useFtps" attribute or something similar and could easily be added to the existing task without requiring a new task at all.

**Comment by bodewig** [comment]
oh, and looking at http://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPSClient.html it would probably good to enable strict host name verification.

**Comment by sonyDeswal** [comment]
> oh, and looking at http://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPSClient.html it would probably good to enable strict host name verification.

Thanks!! Made suggested changes. Please review...

**Comment by bodewig** [comment]
many thanks @sonyDeswal and sorry about the long delay

I've added documentation and a few cosmetic changes with 43214e433 - and also enabled strict host name checking by default. Please have a look and verify I didn't break anything for you.

In addition I'd like to add your name to both CONTRIBUTORS and contributors.xml. If you agree please let me know which name you want me to put in there.

**Comment by sonyDeswal** [comment]
Thanks Stefan.
It works. Please use my Name as Santosh R. Dhariwal, if possible.
Regards,Santosh Dhariwal
    On Thursday, December 16, 2021, 11:34:15 PM GMT+5:30, Stefan Bodewig ***@***.***> wrote:  
 
 


many thanks @sonyDeswal and sorry about the long delay

I've added documentation and a few cosmetic changes with 43214e4 - and also enabled strict host name checking by default. Please have a look and verify I didn't break anything for you.

In addition I'd like to add your name to both CONTRIBUTORS and contributors.xml. If you agree please let me know which name you want me to put in there.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bodewig** [comment]
thank you

**Pull request merged**
