### PR TITLE
Update manual for subject alternative name attribute of genkey task

### PR DESCRIPTION
**Pull request by jnsnkrllive**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jaikiran** [comment]
I picked the commit which updated just the documentation and merged it to upstream.

**Comment by jnsnkrllive** [comment]
Oops, sorry about the bad commits to CONTRIBUTORS and others. I'm still trying to figure out the best way to do this stuff on GitHub. Thanks for picking up the one good commit to merge.

**Pull request closed without merging**
