### PR TITLE
junitlaucher legacy-xml: don't loose exception from @BeforeAll

### PR DESCRIPTION
**Pull request by mguillem**
Reports exception occuring in a @BeforeAll method in the TEST-xxx.xml file. Currently the exception is not reported making users blind.

### CODE REVIEW

**Comment by bodewig** [comment]
this is ok to test

**Comment by mguillem** [comment]
The failed test doesn't seem to be related to this PR. Is it possible that it is an issue in the CI system?

**Comment by jaikiran** [comment]
@mguillem You can ignore that failure. That test is known to fail from time to time. This PR looks OK to me and if no one else gets to it first, then I'll merge this tomorrow.

**Comment by jaikiran** [comment]
@mguillem I've merged your patch. Thank you for contributing this.
I forgot to include a comment in the git commit message to auto-close this PR. Can you please close this one yourself?

**Comment by mguillem** [comment]
@jaikiran thanks for quickly applying my PR. Closing.

**Pull request closed without merging**
