### PR TITLE
Support Jakarta Mail in MailLogger

### PR DESCRIPTION
**Pull request by twogee**
Unfortunately, the code is duplicated due to different logging in different objects.

### CODE REVIEW

**Comment by bodewig** [comment]
In the special case of a logger it may be even preferable to not log any message at all as the message would in turn be logged to the same logger again and may never become visible anywhere. I see the existing code has a `log` statement but I wonder whether this is just an oversight. There are usages of `System.err/out` which may be the better choice.

**Comment by twogee** [comment]
I reason that it might be preferable to have those messages in the log at higher verbosity. Would adding a new interface to provide implementations of log create backwards compatibility problems?

**Comment by bodewig** [comment]
given this all happens in `buildFinished` and it will not be called again after that, my fear of causing a cycle is unfounded.

**Comment by Wade-tech** [comment]
Hi ,tomcat10 change javax.* namespace to jakarta.*， Does ant now support jakarta.mail?

**Comment by bodewig** [comment]
https://ant.apache.org/manual/Tasks/mail.html - Ant 1.10.13.

**Comment by Wade-tech** [comment]
Thanks, JakartaMimeMailer.java use jakarta.mail . I downdload org.apache.ant-ant-1.10.13 jar(url:https://mvnrepository.com/artifact/org.apache.ant/ant/1.10.13). In this jar , not found JakartaMimeMailer.java , i'm confused
image

**Comment by jaikiran** [comment]
Hello @Wade-tech, it will be present in the ant-jakartamail artifact which is here  https://repo1.maven.org/maven2/org/apache/ant/ant-jakartamail/1.10.13/

**Comment by Wade-tech** [comment]
Thanks

**Pull request merged**
