### PR TITLE
Microoptimization. Followup to commit 5f20b99140fb4ec958a6d540b9df7b3…

### PR DESCRIPTION
**Pull request by YoshikiHigo**
This commit includes a very small optimization, which is a followup to commit 5f20b99140fb4ec958a6d540b9df7b3c08312b40.

Yoshiki, Shinpei, Hideaki, and Mei.

### CODE REVIEW

**Comment by bodewig** [comment]
please see the three lines of comment just above the line you've changed, this "micro-optimization" would break builds.

**Comment by YoshikiHigo** [comment]
I'm very sorry for my careless mistake.
Please ignore this pull request.

**Comment by bodewig** [comment]
we all make mistakes, no problem. Sorry if I sounded rude. Your contributions are very much appreciated.

Could you please close this PR? I can't do it myself (easily).

**Comment by YoshikiHigo** [comment]
Thank you.
I'll close this pull request.

**Pull request closed without merging**
