### PR TITLE
Use newer third party libraries

### PR DESCRIPTION
**Pull request by twogee**
The initial aim was to avoid NPE when retrieving jasper and automate retrieval of ant-antunit (with exclusion of ant/ant-launcher).

Then I started wondering whether it could be possible to forgo JUnit 3 altogether and update JUnit 4 to 4.12; if there's a good reason for keeping things the way they were, I'd be happy to add automated downloads of both versions and removal of JUnit 3 classes in JUnit 4.

Finally, jakarta regex is updated to the final version 1.4; AFACS, both versions have the same version of bytecode.

### CODE REVIEW

**Comment by bodewig** [comment]
Thank you @twogee 

The idea was you can build a minimal set of Ant (without the optional tasks that have external dependencies) and run the tests for this minimal set without downloading anything external. This will no longer be the case when applying your PR.

I'm totally fine with upgrading JUnit to 4.12, upgrading Regex and the Maven Ant tasks but really would prefer keeping the jars and licenses in lib/optional.

If I can ask for a favor in your future patches, please don't mix whitespace, text changes and functional changes in a single commit. Reviewing your changes to `fetch.xml` is pretty difficult as the important change (adding antunit) is easily overlooked between all the other changes.

**Comment by twogee** [comment]
Sorry about the whitespace -- I can separate all "drive-by" changes into a commit on its own.

Could you please elaborate on having both JUnit 3 and 4? JUnit 4 is Java 5 compatible, and most test cases are migrated to JUnit 4 anyway. If you agree that JUnit 3 is superfluous, then perhaps needs.junit4 property could be removed from build.xml?

**Comment by bodewig** [comment]
Ant's junit task itself is supposed to work with JUnit 3 not only 4, so it is not superfluous at all IMHO,

**Comment by twogee** [comment]
Sorry about confusion 😊 -- here comes a corrected commit.

**Comment by twogee** [comment]
BTW, JUnit license has changed from CPL to EPL.

**Comment by bodewig** [comment]
Thank you.

The junit 4 situation is a bit weird, even more than I recalled it to be. I didn't remember us stripping classes from the jar and don't think this is true for the 4.11 jar in our repo right now (I think we currently rely on junit3 being on the classpath first). I wouldn't bother trying to strip classes in fetch.xml.

We probably need both licenses for JUnit as 3.8.2 sill uses the CPL.

Oh my. Sorry for being a pain.

**Comment by twogee** [comment]
This is exactly why I was looking into it -- those things tend to deteriorate over time 😄

To sum it up, I'll revert stripping, restore CPL and correct the README (that tests rely on JUnit 3 being first on classpath). BTW, pom.xml should be updated with 4.12 as well, I suppose.

**Comment by bodewig** [comment]
:+1:

**Comment by twogee** [comment]
I hope the third time is the charm 😄

A couple of wishes for antunit: it should have ant/ant-launcher as "provided" dependencies and it should have a "tempdir" attribute similar to junit task.

**Comment by bodewig** [comment]
I'll have a look later and try not to be a PITA again.

WRT antunit. https://github.com/apache/ant-antlibs-antunit and you are a committer ;-)

**Comment by bodewig** [comment]
looks good to me - you may want to add a note to WHATSNEW as well

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/3/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/9/

**Comment by twogee** [comment]
I updated WHATSNEW and added a replacement for all legacy logging frameworks. There are more potential updates: Java Mail API, Rhino, Jasper; perhaps they deserve a separate PR?

**Comment by bodewig** [comment]
I don't really think you need a PR - I've upgraded BCEL last week and did so directly. Ant tends to use a "commit then review" model where people look at the commits and things get amended later.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/10/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/5/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/11/

**Comment by bodewig** [comment]
Actually I do not agree with the slf4j change ;-)

What problem are you trying to solve? To me both existing logging backends are legacy and we maintain them for people who want to use them - they'd be disrupted if we switched to different dependencies. I'd be OK with SLF4J or log4j2 integrations as additional components.

**Comment by twogee** [comment]
SLF4J was written by the [author of Log4j](https://en.wikipedia.org/wiki/Log4j) who wrote [an article](https://articles.qos.ch/classloader.html) cataloguing the problems with Commons Logging. When upgrading Jasper, one gets various versions of commons-logging as dependencies; the latest versions depend on slf4j-nop in runtime, though 😄 Log4j is EOL and the latest versions add dependencies on J2EE (see the removed comment in libraries.properties ;-)

**Comment by twogee** [comment]
I reviewed third party libraries that could be updated; the documentation could be more emphatic about jspc being deprecated.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/6/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/12/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/7/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/13/

**Comment by bodewig** [comment]
Thanks, looks good to me.

Unless you want to port it to the 1.9.x branch you don't need to care about Java5 compatibility.

**Comment by twogee** [comment]
I intended it for 1.9.x in particular. I will open a new request for master later (with commons-net 3.6, for example).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/17/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/11/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/12/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/18/

**Comment by twogee** [comment]
I squashed the commits so the change is easier to apply to 1.9.x

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/13/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/19/

**Pull request closed without merging**
