### PR TITLE
Update ScpFromMessage.java

### PR DESCRIPTION
**Pull request by linux1fans**
Does not show progress 100%

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by jaikiran** [comment]
this is ok to test

**Comment by jaikiran** [comment]
This change looks fine to me. Is there a specific name you want us to use to credit you for this change in our contributors list https://github.com/apache/ant/blob/master/CONTRIBUTORS?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Linux/116/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Ant%20Github-PR-Windows/122/

**Comment by linux1fans** [comment]
> This change looks fine to me. Is there a specific name you want us to use to credit you for this change in our contributors list https://github.com/apache/ant/blob/master/CONTRIBUTORS?

wenjing wang

**Pull request closed without merging**
